name: Node.js CI with Docker Build

on:
    pull_request:
      branches:
        - main  # Trigger CI on pull request to main branch
        
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] 

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run lint
        run: |
          npm run lint

      - name: Run tests
        run: |
          npm run test

      - name: Build Docker image
        run: |
          docker build -t my-node-app .
        
      - name: Run Docker container for testing
        run: |
          docker run -d -p 8080:8080 --name my-node-app-container my-node-app

      - name: Wait for the app to start
        run: |
          sleep 10
          curl --fail http://localhost:8080

      - name: Clean up Docker container and image
        run: |
          docker stop my-node-app-container
          docker rm my-node-app-container
          docker rmi my-node-app
