name: CI/CD Pipeline for Node.js with Docker and Knex Migrations

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers for faster builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example .

    # Authenticate with Google Cloud using service account credentials
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Use gcloud SQL Proxy
    - name: Google cloud SQL Proxy
      uses: ahmadnassri/action-google-cloud-sql-proxy@v1
      with:
        key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        connection: ${{ secrets.GCP_CLOUD_SQL_INSTANCE }}
        port: ${{ secrets.DB_PORT }}
        
    # Run the Knex migrations using the Docker container
    - name: Run Knex Migrations
      run: |
        docker run --rm \
          -e DB_HOST=${{ secrets.DB_HOST }} \
          -e DB_PORT=${{ secrets.DB_PORT }} \
          -e DB_USER=${{ secrets.DB_USER }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e DB_NAME=${{ secrets.DB_NAME }} \
          gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example npm run knex migrate:latest


    # Push Docker image to GCR
    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example

    # Deploy the app 
    - name: Deploy to Google Cloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        gcloud app browse  # Or use Kubernetes/GKE deploy, depending on your setup
