name: Deploy 

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker europe-north1-docker.pkg.dev
        docker build -t europe-north1-docker.pkg.dev/$GOOGLE_PROJECT/cloud-rest-api-repo/rest-api-example:latest .
        docker push europe-north1-docker.pkg.dev/$GOOGLE_PROJECT/cloud-rest-api-repo/rest-api-example:latest
    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy rest-api-example-service \
          --image europe-north1.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPOSITORY_NAME}}/rest-api-example:latest\
          --platform managed \
          --allow-unauthenticated 