name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger the pipeline when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # GitHub secret with your service account credentials

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your Google Cloud project ID


      # Step 4: Authenticate Docker to GCR (Google Container Registry)
    - name: Authenticate Docker to GCR
      run: |
        gcloud auth configure-docker gcr.io

      # Step 5: Build and push the Docker image to GCR
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:latest

      # Step 6: Run Knex migrations
    - name: Run Knex migrations
      run: |
        docker run --rm \
          -e DB_CONNECTION_STRING=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }} \
          -e NODE_ENV=production \
          gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:latest \
          npm run knex migrate:latest

      # Step 7: Run Knex seeds
    - name: Run Knex seeds
      run: |
        docker run --rm \
          -e DB_CONNECTION_STRING=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }} \
          -e NODE_ENV=production \
          gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:latest \
          npm run knex seed:run

      # Step 8: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy rest-api-example \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:latest \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --set-env-vars NODE_ENV=production,DB_CONNECTION_STRING=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:5432/${{ secrets.DB_NAME }}