name: Deploy Docker Image to Google Cloud Artifact Registry and Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:${{ github.sha }} .

      # Push Docker image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:${{ github.sha }}

      # Deploy Docker image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy rest-api-example \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rest-api-example:${{ github.sha }} \
            --platform managed \
            --region europe-north1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
